import { Download } from 'lucide-react';
import { Button } from '@/components/ui/button';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { toast } from 'sonner';

interface Transaction {
  id: string;
  amount: number;
  category: string;
  description: string;
  transaction_type: string;
  transaction_date: string;
  upi_handle?: string | null;
}

interface ExportTransactionsProps {
  transactions: Transaction[];
}

export function ExportTransactions({ transactions }: ExportTransactionsProps) {
  const exportCSV = () => {
    if (transactions.length === 0) {
      toast.error('No transactions to export');
      return;
    }

    const headers = ['Date', 'Category', 'Description', 'Type', 'Amount (₹)', 'UPI Handle'];
    const rows = transactions.map(t => [
      new Date(t.transaction_date).toLocaleDateString('en-IN'),
      t.category,
      `"${t.description.replace(/"/g, '""')}"`,
      t.transaction_type,
      t.amount.toString(),
      t.upi_handle || '',
    ]);

    const csv = [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `rupeerise-transactions-${new Date().toISOString().split('T')[0]}.csv`;
    link.click();
    URL.revokeObjectURL(url);
    toast.success('CSV exported! 📄');
  };

  const exportPDF = () => {
    if (transactions.length === 0) {
      toast.error('No transactions to export');
      return;
    }

    const printWindow = window.open('', '_blank');
    if (!printWindow) {
      toast.error('Please allow popups to export PDF');
      return;
    }

    const totalExpense = transactions
      .filter(t => t.transaction_type === 'expense')
      .reduce((sum, t) => sum + t.amount, 0);
    const totalIncome = transactions
      .filter(t => t.transaction_type === 'income')
      .reduce((sum, t) => sum + t.amount, 0);

    const rows = transactions.map(t => `
      <tr>
        <td style="padding:8px;border-bottom:1px solid #e5e7eb">${new Date(t.transaction_date).toLocaleDateString('en-IN')}</td>
        <td style="padding:8px;border-bottom:1px solid #e5e7eb">${t.category}</td>
        <td style="padding:8px;border-bottom:1px solid #e5e7eb">${t.description}</td>
        <td style="padding:8px;border-bottom:1px solid #e5e7eb;color:${t.transaction_type === 'expense' ? '#dc2626' : '#16a34a'}">${t.transaction_type === 'expense' ? '-' : '+'}₹${t.amount.toLocaleString('en-IN')}</td>
      </tr>
    `).join('');

    printWindow.document.write(`
      <html><head><title>RupeeRise Transactions</title></head>
      <body style="font-family:system-ui;padding:40px;max-width:800px;margin:0 auto">
        <h1 style="color:#0d9488;margin-bottom:4px">RupeeRise AI</h1>
        <p style="color:#6b7280;margin-bottom:24px">Transaction Report — ${new Date().toLocaleDateString('en-IN', { month: 'long', year: 'numeric' })}</p>
        <div style="display:flex;gap:24px;margin-bottom:24px">
          <div style="padding:16px;background:#f0fdf4;border-radius:8px;flex:1"><strong>Income</strong><br/>₹${totalIncome.toLocaleString('en-IN')}</div>
          <div style="padding:16px;background:#fef2f2;border-radius:8px;flex:1"><strong>Expenses</strong><br/>₹${totalExpense.toLocaleString('en-IN')}</div>
          <div style="padding:16px;background:#f0f9ff;border-radius:8px;flex:1"><strong>Net</strong><br/>₹${(totalIncome - totalExpense).toLocaleString('en-IN')}</div>
        </div>
        <table style="width:100%;border-collapse:collapse">
          <thead><tr style="background:#f9fafb">
            <th style="padding:8px;text-align:left">Date</th>
            <th style="padding:8px;text-align:left">Category</th>
            <th style="padding:8px;text-align:left">Description</th>
            <th style="padding:8px;text-align:left">Amount</th>
          </tr></thead>
          <tbody>${rows}</tbody>
        </table>
        <p style="color:#9ca3af;margin-top:24px;font-size:12px">Generated by RupeeRise AI on ${new Date().toLocaleString('en-IN')}</p>
      </body></html>
    `);
    printWindow.document.close();
    printWindow.print();
    toast.success('PDF ready to print! 🖨️');
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button variant="outline" size="sm" className="gap-2">
          <Download className="w-4 h-4" />
          <span className="hidden sm:inline">Export</span>
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={exportCSV}>
          📊 Export as CSV
        </DropdownMenuItem>
        <DropdownMenuItem onClick={exportPDF}>
          📄 Export as PDF
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
